const SERVER_PORT = 3000
const STAUS_CODE_CREATED = 201
const STAUS_CODE_NOT_IMPLEMENTED = 501
const STAUS_CODE_INTERNAL_SERVER_ERROR = 500
const STAUS_CODE_BAD_REQUEST = 400
const SALT_ROUND = 5
const LOGIN_FAIL_MASSAGE = 'Login failed please check username/password'
const LOGIN_SUCCESS_MASSAGE = 'Login Success'

module.exports ={
    SERVER_PORT,
    STAUS_CODE_CREATED,
    STAUS_CODE_NOT_IMPLEMENTED,
    SALT_ROUND,
    LOGIN_FAIL_MASSAGE,
    LOGIN_SUCCESS_MASSAGE,
    STAUS_CODE_INTERNAL_SERVER_ERROR,
    STAUS_CODE_BAD_REQUEST
}   

